# see https://github.com/caronc/apprise for more examples

# examples:
#
#   tgram://{bot_token}/{chat_id}
#   discord://{WebhookID}/{WebhookToken}
#   mailtos://{user}:{password}@{host}
#   twitter://user@CKey/CSecret/AKey/ASecret

#   dbus://
#   qt://
#   glib://
#   kde://
#   gnome://
#   macosx://
#   windows://

# /config/apprise.yaml
# Our Apprise Configuration File leveraging Tagging
#
urls:
  # Set up a email notification
  - "mailtos://bauke.molenaar:qzujjjvwvdxeuvqw@gmail.com":
    - tag: me, family
      to: myuser@gmail.com
    - tag: family
      to: myspouse@gmail.com, mykid@gmail.com
 
  # Our DevOps team at work
  - "tgram://1823423007:AAEdgfiJbNL1G9zEi5LweECJsda_pIbCdoM/639276511":
    - tag: devops