# see https://github.com/caronc/apprise for more examples

# examples:
#
#   tgram://{bot_token}/{chat_id}
#   discord://{WebhookID}/{WebhookToken}
#   mailtos://{user}:{password}@{host}
#   twitter://user@CKey/CSecret/AKey/ASecret

#   dbus://
#   qt://
#   glib://
#   kde://
#   gnome://
#   macosx://
#   windows://

# /config/apprise.yaml
# Our Apprise Configuration File leveraging Tagging
#
urls:
  # Set up a email notification
  # ⚠️ Replace with your own credentials or use environment variables
  - "mailtos://USER:PASSWORD@gmail.com":
    - tag: me, family
      to: myuser@gmail.com
    - tag: family
      to: myspouse@gmail.com, mykid@gmail.com
 
  # Our DevOps team at work
  # ⚠️ Replace with your own bot token and chat ID
  - "tgram://BOT_TOKEN/CHAT_ID":
    - tag: devops